server {
    listen 80;
    server_name localhost _;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://commerce.api:5000/\;
    }
    location /auth/ {
        proxy_pass http://commerce.api:5000/auth/\;
    }
}
